### ISSUE TITLE
Simplified relationships?

### ISSUE THREAD

**Issue by ubitux** [scriptin/topokanji#1]
Hi,

I know this repository is not really maintained but I've been trying to play with the data. This is probably due to the original derived database, but some relationships between kanji look just wrong. Just to pick a few examples from the beginning of `1-to-1.txt`:

- 七 and 儿
- 乃 and 刀
- 匸 and 匚

They kind of look the same (sometimes) but that means they can not be used to depict the construct parts of a given Kanji. I might be misunderstanding the purpose of the database though...

The reason I'm so bothered with this is because I've been trying to use your database to represent the relationships between kanjis (as in: linking a kanji to its constituents) and the results have been disappointing to say the least.

Here is a very basic Python script I experimented with:
```python
import networkx as nx
import matplotlib.pyplot as plt

plt.rcParams['font.sans-serif'] = 'Sazanami Gothic'
G = nx.Graph()
with open('1-to-1.txt') as f:
    for line in f:
        edge = line.split()
        if not edge or '0' in edge:
            continue
        G.add_edge(*edge)
nx.draw(G, with_labels=True)
plt.show()
```

As expected, with all the kanjis it's a unusable mess:
![full-zoom-out](https://user-images.githubusercontent.com/34467/115962764-28148480-a51d-11eb-88e8-329d0fb531d0.png)

But zooming still feels like some kind of 惡の華 spin-off rather than exploitable data:
![full-zoom-in](https://user-images.githubusercontent.com/34467/115962786-3c588180-a51d-11eb-983a-8cb2a64a012a.png)

Now if I filter only the first 100/5727 edges:
![100](https://user-images.githubusercontent.com/34467/115962798-45e1e980-a51d-11eb-9e52-5ce60f26094e.png)

We can see already that links are not very helpful...

I'm sorry if this is kind of out of scope to this project.

**Comment by scriptin** [comment]
Hello!

The purpose of **dependencies** is to establish the optimal order of learning. In your examples:

- 七 and 儿 are related because they share the "hook" part (the right half of 儿)
- 乃 and 刀 are related because they share the "bent line" part (the left "leg")
- 匸 and 匚 are related because they share the "L" shape at the bottom

In each case, the idea is that before one learns the 1st kanji/component, they should first learn the 2nd one. In some cases, this order is opinionated. For example, 礻and 主 are neither related nor similar in shape (see [this article about 示 radical](https://en.wikipedia.org/wiki/Radical_113)), but I had to add this kind of pairs to establish _some_ ordering suitable for western learners.

In any case, dependencies are not what you're looking for.

> I've been trying to use your database to represent the relationships between kanjis (as in: linking a kanji to its constituents)

What you're looking for are **decompositions**, which I found in the [CJK decompositions database](https://archive.codeplex.com/?p=cjkdecomp) ([mirror](https://github.com/amake/cjk-decomp)), and later added some more intuitive [overrides](https://github.com/scriptin/topokanji/blob/master/data/cjk-decomp-override.txt). The format of this data is more complicated, but it provides what you're looking for.

Also, since that CJK decompositions database is no longer maintained, you can take a look at this repo: <https://github.com/cjkvi/cjkvi-ids>. At a quick glance, it provides very similar data.

Hope this helps. Feel free to ask more questions.

**Comment by ubitux** [comment]
> In each case, the idea is that before one learns the 1st kanji/component, they should first learn the 2nd one. In some cases, this order is opinionated. For example, 礻and 主 are neither related nor similar in shape (see [this article about 示 radical](https://en.wikipedia.org/wiki/Radical_113)), but I had to add this kind of pairs to establish _some_ ordering suitable for western learners.

I see; that makes sense.

> In any case, dependencies are not what you're looking for.
> [,,,]
> What you're looking for are **decompositions**, which I found in the [CJK decompositions database](https://archive.codeplex.com/?p=cjkdecomp) ([mirror](https://github.com/amake/cjk-decomp)), and later added some more intuitive [overrides](https://github.com/scriptin/topokanji/blob/master/data/cjk-decomp-override.txt). The format of this data is more complicated, but it provides what you're looking for.
> 
> Also, since that CJK decompositions database is no longer maintained, you can take a look at this repo: https://github.com/cjkvi/cjkvi-ids. At a quick glance, it provides very similar data.

Thanks a lot! I used `ids.txt` from https://github.com/cjkvi/cjkvi-ids to build a tree. I got exactly what I was looking for. topokanji database was then very useful to filter down a subset of it.

Unfortunately the graph is still pretty terrible and unusable anyway, but I was kinda ready for that...

> Hope this helps. Feel free to ask more questions.

You provided me everything I needed, thanks again.
